name: AI Code Review CI/CD

# Trigger the workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    # Environment variables (from GitHub Secrets)
    env:
      HF_TOKEN: ${{ secrets.HF_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_PAT }}

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up Python
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Run tests
      - name: Run tests
        run: |
          pytest tests/ --maxfail=1 --disable-warnings -q

      # 5. Lint code (optional)
      - name: Lint code
        run: |
          pip install flake8
          flake8 .

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # 6. Build Docker image
      - name: Build Docker image
        run: |
          docker build -t ai-code-review:latest .

      # 7. Log in to Docker Hub
      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 8. Push Docker image
      - name: Push Docker image
        run: |
          docker tag ai-code-review:latest ${{ secrets.DOCKER_USERNAME }}/ai-code-review:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/ai-code-review:latest
